version: '3.8'

services:
  github-service:
    image: github-service:latest
    build: ./github-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - app-network

  users-service:
    image: users-service:latest
    build: ./users-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8001:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  dashboard-service:
    image: dashboard-service:latest
    build: ./dashboard-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
